Space... The final frontier...
 These are the voyages of the Starship Enterprise.
 Its continuing mission:
 To explore strange new worlds...
 To seek out new life; new civilisations...
 To boldly go where no one has gone before!